### ISSUE TITLE
Keep track of SPRING and FASTQ files based on flow cells

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#2131]
### Urgent part (Patched)
When demultiplexing flow cells cg [removes any previous instances](https://github.com/Clinical-Genomics/cg/blob/38aec5ae85ea212f51c946f891c490fa9440406a/cg/cli/demultiplex/demux.py#L62-L69) of the flow-cell in housekeeper. This deletes the sample sheet, but more notably any SPRING or FASTQ file associated with the samples run on the flow cell. Unfortunately the files are not filtered on flow cell, so any SPRING and FASTQ files from previous sequencing runs will be removed both from disc and database. By some fluke this does not happen for new flow cells since they are not present in status_db and thus have no samples to iterate trough ([check](https://github.com/Clinical-Genomics/cg/blob/38aec5ae85ea212f51c946f891c490fa9440406a/cg/meta/demultiplex/delete_demultiplex_api.py#L218-L219) and [loop](https://github.com/Clinical-Genomics/cg/blob/38aec5ae85ea212f51c946f891c490fa9440406a/cg/meta/demultiplex/delete_demultiplex_api.py#L103-L104)).

### Little less urgent part
At the moment there is no way of finding which SPRING file comes from which flow cell since they are not tagget with the flow cell name in housekeeper. Therefore when demultiplexing old flow cells FASTQ file can be added to sample which already have the same reads but in SPRING format. We need to add the tags for all new SPRING, SPRING-metadata and (decompressed-) FASTQ  files. In order to work with them systematically. We also need to retroactively add it to all current files.

## Suggested solution
- [x] Turn of deletion of data when demultiplexing #2144 
- [x] Add the flow cell name as a tag for all SPRING files, when compressing. #2475 
- [x] Add the flow cell name as a tag for all SPRING-metadata files, when compressing. #2475 
- [x] Add the flow cell name as a tag for FASTQ files when decompressing them. #2473 
- [ ] Curate the database of inaccurate data
    - [x] Parse SPRING, SPRING-metadata and FASTQ file names and add FC tag i not added #2513 
    - [x] If no FC in name we need to decompress and read the FASTQ to get the FC name #2530
    - [ ] Clean housekeeper of any duplicated data (ie FASTQ and SPRING from the same flow cell and lane)
- [ ] https://github.com/Clinical-Genomics/cg/issues/2541
## This can be closed when
- [ ] Only files from the currently demultiplexing flow cell are removed

**Comment by karlnyr** [comment]
We did some testing to see if we could get all spring files - check if they have a flow cell name in the name -  and if not then we decompress it and check the first row for the fastq-header and extract the fastq-header from there:

```Command
[P_crunchy] $ spring -d --decompress-range 1 1 -r -i sample.spring -o output.fastq
Temporary directory: ./tmp.fa37JncCHr/
Starting decompression...
Untarring tar archive ...
Untarring archive done!
Decompressing ...
Decompression done!
Total time for decompression: 34 s
[P_crunchy] $ spring -d --decompress-range 1 1 -r -i sample.spring -o output.fastq -t 16
Temporary directory: ./tmp.fa37JncCHr/
Starting decompression...
Untarring tar archive ...
Untarring archive done!
Decompressing ...
Decompression done!
Total time for decompression: 34 s
[P_crunchy] 49s $ spring -d --decompress-range 1 1 -r -i sample.spring -o output.fastq -t 1
Temporary directory: ./tmp.fa37JncCHr/
Starting decompression...
Untarring tar archive ...
Untarring archive done!
Decompressing ...
Decompression done!
Total time for decompression: 107 s
```

It seems like running the program with more threads does not speed up the process by 2x - however, reducing the number of threads by 8x only took the program 3x more time - so we could perhaps gain some speed by doing more jobs in parallel since it is pretty efficient with only 1 thread.

**Comment by diitaz93** [comment]
Regarding "*Add the flow cell name as a tag for all SPRING files, when compressing.*", would it be adding the tag with the flow cell id to `spring_tags` here?
```python
cg/meta/compress/compress.py

    def update_fastq_hk(
        self,
        sample_id: str,
        compression_obj: CompressionData,
        hk_fastq_first: File,
        hk_fastq_second: File,
    ) -> None:
        """Update Housekeeper with compressed FASTQ files and SPRING metadata file."""
        version: Version = self.hk_api.last_version(sample_id)
        spring_tags: List[str] = [sample_id, SequencingFileTag.SPRING]
        spring_metadata_tags: List[str] = [sample_id, SequencingFileTag.SPRING_METADATA]
        LOG.info(f"Updating FASTQ files in Housekeeper for {sample_id}")
        LOG.info(
            f"{compression_obj.fastq_first}, {compression_obj.fastq_second} -> {compression_obj.spring_path}, "
            f"with tags {spring_tags}"
        )
        LOG.info(f"Adds {compression_obj.spring_metadata_path}, with tags {spring_metadata_tags}")
        if self.dry_run:
            return

        LOG.info("Updating files in Housekeeper...")
        if files.is_file_in_version(version_obj=version, path=compression_obj.spring_path):
            LOG.info("SPRING file is already in Housekeeper")
        else:
            LOG.info("Adding SPRING file to Housekeeper")
            self.hk_api.add_and_include_file_to_latest_version(
                bundle_name=sample_id, file=compression_obj.spring_path, tags=spring_tags
            )
            self.hk_api.commit()

        if files.is_file_in_version(version_obj=version, path=compression_obj.spring_metadata_path):
            LOG.info("SPRING metadata file is already in Housekeeper")
        else:
            LOG.info("Adding SPRING metadata file to Housekeeper")
            self.hk_api.add_and_include_file_to_latest_version(
                bundle_name=sample_id,
                file=compression_obj.spring_metadata_path,
                tags=spring_metadata_tags,
            )
            self.hk_api.commit()

        self.delete_fastq_housekeeper(
            hk_fastq_first=hk_fastq_first, hk_fastq_second=hk_fastq_second
        )
```

**Comment by diitaz93** [comment]
I am wondering if this function is capturing characters that are not the flow cell id and assigning them as such:
```python
    def get_flow_cell_id(self, fastq_path: Path) -> str:
        """Extract the flow cell id from a fastq path assuming flow cell id is the first word in the file name."""
        flow_cell_id: str = ""
        regexp = r"(\A[A-Z0-9]+)"
        try:
            flow_cell_id: str = re.search(regexp, fastq_path.name).group()
        except AttributeError as error:
            LOG.error(error)
            LOG.info(f"Could not find flow cell id from fastq path: {fastq_path.as_posix()}")
        return flow_cell_id
```

**Comment by Vince-janv** [comment]
### Tasks decided upon:
- [ ] Add sample_id as tag for FASTQ files in post-processing. @diitaz93 
- [ ] Add sample_id for already created FASTQ files. @diitaz93 
- [ ] Prepare PRs for passing tags between SPRING and FASTQ files. @islean 

- [ ] Investigate how many SPRING files have the flow cell id in their path. @islean 
- [ ] Write script to add flow cell tag for the SPRING files above.
- [ ] Write script for SPRING files where the sample only has one flow cell and add that as a tag and modify path to prepend flow cell id (for SPRING file, optional FASTQ file, meta-data file and content of meta-data file).
- [ ] Write script that decompresses SPRING files and parses the flow cell id from the results and modify path  to prepend flow cell id (for SPRING file, optional FASTQ file, meta-data file and content of meta-data file).

**Comment by diitaz93** [comment]
I would also add to the list of tasks (once all the flow cell tags have been added) to verify that the flow cell tag matches the flow cell in statusDB. What do you think? @islean @Vince-janv

**Comment by islean** [comment]
I think that sounds great! @diitaz93

**Comment by Vince-janv** [comment]
> I would also add to the list of tasks (once all the flow cell tags have been added) to verify that the flow cell tag matches the flow cell in statusDB. What do you think? @islean @Vince-janv

I think we'll get quite a few samples where this is not the case, but it would be nice to get some more info on what might have happened with these... 🤔

**Comment by islean** [comment]
We can close this now right @diitaz93 @Vince-janv ?

**Comment by islean** [comment]
Or are we waiting on https://github.com/Clinical-Genomics/cg/issues/2541?

**Comment by Vince-janv** [comment]
Yes we can close it! 🎈
