### ISSUE TITLE
Roadmap for implementing automatic archiving in cg

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#2205]
## Description
This issue breaks down the last features needed to implement automatic archiving of hospital data:

### Left to write
- [x] Archive files IO
    - [x] Exempt files already archived
    - [x] Change settings to remove file on archive
    - [x] Add metadata to archived files https://github.com/Clinical-Genomics/cg/pull/2799
        - [x] Customer name
        - [x] Sample name
        - [x] Sequenced_at?
        - [x] prep-category (from apptag)?
        - [x] ticket number?
- [x] Retrieve files #2674 
    - [x] On case start check if spring files are archived. If yes, fetch them IO
- [x] Clean retrieved files after certain date IO https://github.com/Clinical-Genomics/cg/pull/2815
    - [x] Query hk for archived files with retrieved older than certain date
    - [x] Remove retrieved_at and retrieval_id
- [x] Create systemd-services
    - [x] Archive https://github.com/Clinical-Genomics/servers/pull/1230
    - [x] Clean https://github.com/Clinical-Genomics/servers/pull/1328
- [x] Check that compression does not create new SPRING files if FASTQ files are present but SPRING files are archived https://github.com/Clinical-Genomics/cg/pull/2814

### How to implement
- [x] Decide on which customer to start with (start with small customer, finish with cust002)
    - Here's the list: https://docs.google.com/spreadsheets/d/10CSnNFVeAHnb4VoxcNMh0YTIHSjqY6M_/edit#gid=1259760810 
- [x] Alert Karolinska that we will start sending files
- [x] Maybe 200 per day?
- [x] Finish at 200 per hour?
