### ISSUE TITLE
Balsamic v13 release changes

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/cg#2447]
## Description

Issue for monitoring the changes required in CG/Servers for the Balsamic v13 release.

## Tasks
- [x] Remove concatenation for Balsamic (108b50871a5e692f5dc07f7924943120acb9e045)
- [x] Rename observations CLI options (1033b3c464cd785c628bc9a4c67d0943daf66931)
- [x] Add cadd annotation CLI option (aeb8431ddf02abc4ea8d3faf29a0d4445769d99c)
- [x] Add cadd path to servers (https://github.com/Clinical-Genomics/servers/pull/1109)
- [x] Add `--cache-version` option to Balsamic config case (66dcab4c43885142f582462b54ef88d2e33a3c94)
- [x] Adapt Balsamic analysis config model according to the new structure (9d4e3a9e88f032ac0a5a5a0d8933df6d808591ef)
- [x] Update metrics model and `PERCENT_DUPLICATION` calculation (used to be `PERCENT_DUPLICATION_R<1/2>`, now matching TGA with `PERCENT_DUPLICATION`) (a289ab1fc8417f6131a53f76c2cf71d6d91c66d3)
- [x] Execute Balsamic from its environment:
  - [x]  CG (4c6a1af922cee48ef2692c6fbea8f43950734188 & bb5584f9fea6fa3212d3228edc4c13b1f8157c59)
  - [x] Servers (https://github.com/Clinical-Genomics/servers/pull/1128)
- [x] Required for GENS implementation 
   - [x] New reference files for starting WGS cases: `genome-interval`, `gnomad-af5` and `gens-coverage-pon` (MALE / FEMALE)
     - [x] Servers: https://github.com/Clinical-Genomics/servers/pull/1173
     - [x] CG: 5dc14cd952974f0a851ba6ca748b97646d5d794d 
   - [x] Store and upload GENs output files
     - [x] Store in HK (Hermes) (https://github.com/Clinical-Genomics/hermes/pull/86)
     - [x] Upload to GENS (CG) (7d648f191927ee4811812f11fc143cc720d6c395)
     - [x] Modify scout_load.yaml to use LIMS-ID as sampleid to fix GENS links in Scout https://github.com/Clinical-Genomics/cg/pull/2650
- [ ] ~GENs PON workflow~
   - [ ] ~New command-line for CNVkit PON creation`--pon-creation-type CNVkit`~
   - [ ] ~New PON creation option for PON-workflow for GENS (remove target-bed argument), add `--pon-creation-type GENS_MALE/GENS_FEMALE --genome-interval referencepath`~
