### ISSUE TITLE
Add optional parameters for cg downsample samples

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#3327]
As a bioinformatician,
I want to be able to set the action in StatusDB, the ticket number, customer, pipeline and delivery type when downsampling a case,
So that new cases do not have to be manually modified to avoid starting automatically and having incorrect information.

# Acceptance Criteria

- [x] Optional parameter to set action in StatusDB
- [x] Optional parameter to set the customer in StatusDB
- [x] Optional parameter to set the workflow/pipeline in  StatusDB
- [x] Optional parameter to set delivery type in StatusDB

# Notes

- Additional information.
- Dependencies.
- Related user stories.

# Implementation plan

- [ ] https://github.com/Clinical-Genomics/cg/pull/3329

**Comment by fevac** [comment]
@ChrOertlin @islean thoughts about this? I would really like to get this feature so I don't have to be manually changing information from downsampled cases

**Comment by ChrOertlin** [comment]
Are these all case level parameters?

**Comment by islean** [comment]
> @ChrOertlin @islean thoughts about this? I would really like to get this feature so I don't have to be manually changing information from downsampled cases

Should be quite doable. I guess we should make them all optional though.

**Comment by fevac** [comment]
> Are these all case level parameters?

yes

**Comment by Vince-janv** [comment]
Validation and downsampling are not prioritised at the moment. CG as an organisation needs a solution for this, but it is unclear cg should take care of it
