### ISSUE TITLE
Harmonise microSALT delivery options

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#3339]
### Description
For files delivered to our delivery-server (Caesar) there are two options either `ANALYSIS` or `FASTQ+ANALYSIS` (or only `FASTQ` if no analysis is needed). For microSALT cases these are instead called `FASTQ_QC` and `FASTQ_QC+ANALYSIS`. The QC part is redundant and has little meaning. 

microSALT orders should only have the options ANALYSIS and FASTQ+ANALYSIS to harmonise the options
# Acceptance Criteria

- [ ] Data delivery options for microSALT or not an exception to the rules for the other workflows

# Notes

- Removing QC should not change any logic (as we use case.data_delivery.contains("FASTQ"/"ANALYSIS")) which will still work
- Some documentation in atlas might need to change
# Implementation plan

- [ ] The excel orderform for microSALT is updated with the general options
- [ ] The FE options in the dropdown are removed
- [ ] Remove the old options from `cg.constants.constants.DataDelivery`

**Comment by Vince-janv** [comment]
With the new delivery re-written last year I see no point in spending time on this before replacing microSALT
