### ISSUE TITLE
Sample sheets for single-sample lanes failing validation

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#3404]
Filled together with @Karl-Svard 

As a production user who encounters a sample sheet of a flow cell with **one sample per lane** and that has no index in its samples,
I want the sample sheet not to fail validation,
So that the flow cell can be automatically demultiplexed and post-processed.

# Acceptance Criteria

- [x] The change should only happen when there is one sample per lane that has no indexes
- [x] The sample sheet has to be accepted by DRAGEN in the demultiplex
- [x] The sample sheet has to allow post-processing
...

# Notes
This has happened twice in the last weeks, most likely from flow cells whose sample sheets were regenerated from Bcl2fastq to BCLConvert. One of the flow cells in H3YVCALXX

# Clarification
The validation cg performs on a sample sheet disallows samples with no indices even though they are permitted by the demux software. 

Also the samplesheet generated by cg is not accepted by the validation on dragen.

# Implementation plan
- [ ] Fix generation/validation of OverrideCycles for the flow cells with only one sample per lane and samples without indices
- [ ] Remove the barcode mismatch columns from this flow cell
- [ ] Update tests with this new flow cell (add this case to canonical flow cells)

**Comment by diitaz93** [comment]
## Technical refinement
1. Modify the OverrideCycles validator in cg/apps/demultiplex/sample_sheet/override_cycles_validator.py so that it parses correctly null indexes

**Comment by diitaz93** [comment]
Affected FC: `161206_ST-E00201_0170_BH57JWALXX`

**Comment by diitaz93** [comment]
Happened again to flow cell `160401_ST-E00266_0079_BHK3YTCCXX`, bumping the priority of this

**Comment by diitaz93** [comment]
@Karl-Svard found the root cause of this issue in LIMS and patched it for the affected indexes. Re-open and inform KSV if this happens again
