### ISSUE TITLE
Replace DeliverAPI with DeliveryAPI

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/cg#3433]
As a bioinformatician,
I want a maintainable and unambiguous delivery API,
So that the delivery to Caesar is more understandable and error-free.

Some work has already been done:
https://github.com/Clinical-Genomics/cg/blob/ff34ed99c425f0fd0380b3db663791b38d28ebf0/cg/meta/delivery/delivery.py#L22

# Acceptance Criteria

- [ ] Files delivered successfully to Caesar
- [ ] Removed unnecessary logic from certain deliveries (FastQ, Fastq-QC, etc.)

# Notes

- Related user stories. Some should be addressed, ideally, taking into account the new delivery API:
    - https://github.com/Clinical-Genomics/cg/issues/3432
    - https://github.com/Clinical-Genomics/cg/issues/2603
    - https://github.com/Clinical-Genomics/cg/issues/3339
    - https://github.com/Clinical-Genomics/cg/issues/2304

# Implementation plan

- [x] Extract the files to be delivered per workflow and delivery type: https://github.com/Clinical-Genomics/cg/pull/3029
- [x] Report the delivered files in the delivery report: https://github.com/Clinical-Genomics/cg/pull/3029
- [ ] Add commands for the updated delivery API
- [ ] Implement Rsync to Caesar following new file centered delivery logic
- [ ] Replace the `DeliverAPI` with the `DeliveryAPI` in the clinical uploads

**Comment by ChrOertlin** [comment]
closing in favour of: https://github.com/Clinical-Genomics/cg/issues/3627
