### ISSUE TITLE
Remove Balsamic QC

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#3918]
# Descripion
The workflow Balsamic QC has never and will probably never be used by customers. We are supporting it and maintaining logic for cases with this workflow set. Removing it would reduce the amount of logic we have to maintain.

## User story
As a developer,
I want to remove the Balsamic QC workflow and all code tied to it,
So that we don't have to maintain unused code.

# Work impact

Answer the following questions:
- How much time would be saved by implementing this feature on a weekly basis?
    - This would reduce development time in all projects dealing with the order flow
- How many users are affected by this issue?
    - All developers
- Are customers affected by this issue?
    - No customers are using this

# Work items

- [x] Janus https://github.com/Clinical-Genomics/Janus/pull/29
- [x] Order portal https://github.com/Clinical-Genomics/clinical-genomics-ui/pull/695
- [x] Trailblazer (codebase) https://github.com/Clinical-Genomics/trailblazer/pull/517
- [x] Clinical-Genomics/trailblazer#518
- [x] servers https://github.com/Clinical-Genomics/servers/pull/1488
- [x] #4190
- [x] cg (codebase) https://github.com/Clinical-Genomics/cg/pull/4192
- [x] Hermes https://github.com/Clinical-Genomics/hermes/pull/128
- [x] Atlas https://github.com/Clinical-Genomics/atlas/pull/3380
- [x] Last minute bug fix https://github.com/Clinical-Genomics/cg/pull/4195

# Acceptance Criteria

- [x] Customers can no longer place Balsamic QC orders
- [x] All logic partaining to Balsamic QC is removed

# Notes

- The order type should also be removed from the FE
- All 8 cases in the database with data_analysis='balsamic-qc' can be set to just 'balsamic'

**Comment by henrikstranneheim** [comment]
Remove QC code here: https://github.com/Clinical-Genomics/cg/pull/3924

**Comment by henrikstranneheim** [comment]
Hermes: https://github.com/Clinical-Genomics/hermes/pull/128

**Comment by henrikstranneheim** [comment]
Servers: https://github.com/Clinical-Genomics/servers/pull/1488

**Comment by diitaz93** [comment]
## Initial technical refinement/ questions: Listing places where we would need to touch any code
- Balsamic QC is present in the following repositories (at least):

- [ ] cg
- [ ] Hermes
- [ ] Servers
- [ ] Trailblazer
- [ ] CiGRID
- [ ] clinical-genomics-ui
- Any other?? Arnold? Janus?

- How would this affect Scout?
- How would this affect gens?
- How would this affect locusDB?
- How would this affect Housekeeper? Is there a tag for balsamic-qc? What to do with files tagged with this?

We could start by removing BalsamicQC as an order option in the order portal, so that we don't get any more data

**Comment by diitaz93** [comment]
Side idea: Should we have a protocol for deprecating workflows? This can be a chance to create this protocol and documenting it

**Comment by diitaz93** [comment]
## Questions for refinement
- What to do with the existing database entries in statusDB? https://cg-statusdb.scilifelab.se/admin/case/?flt1_17=balsamic-qc

**Comment by diitaz93** [comment]
> ## Questions for refinement
> * What to do with the existing case entries in statusDB? [cg-statusdb.scilifelab.se/admin/case?flt1_17=balsamic-qc](https://cg-statusdb.scilifelab.se/admin/case/?flt1_17=balsamic-qc)
> * What to do with the existing Analysis entries in statusDB?
> * What to do with the existing Analysis entries in Trailblazer?

Turn all those instances from `balsamic-qc` to `balsamic`

**Comment by diitaz93** [comment]
All tasks completed
