### ISSUE TITLE
Refactor OrderAPI

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/cg#949]
Improvements to the parsing of the json and excel sheets is necessary. This will be beneficial when we move the orderportal into its own service

- [x] Use pydantic when sending information from orderportal (`submit`) to backend  #960 
- [x] Validate orderforms (excel and json) (NOT `submit`) with pydantic when uploading from orderportal #924 
- [ ] Validate orders when submitted (this is a dict) with pydantic when `submit` #961
- [ ] Refactor the process of storing samples/cases/pools, adding lims info etc in order API (this issue)

**Comment by Mropat** [comment]
Exists as a project
